# Used https://access.redhat.com/labs/ocpupgradegraph/update_path/

kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
archiveSize: 12 
mirror:
  platform:
    channels:
      - name: stable-4.19
        type: ocp
        minVersion: 4.19.6
        maxVersion: 4.19.18
      - name: stable-4.20
        type: ocp
        minVersion: 4.20.3
        #maxVersion: 4.20.4
    graph: true
  operators:
    # Red Hat Operators Catalog v4.20
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20
      packages:

      # OpenShift Virtualisation and Metal LB
      - name: kubevirt-hyperconverged
        channels:
          - name: stable
      - name: metallb-operator
        channels:
          - name: stable
      - name: nmstate-operator
        channels: 
          - name: stable
      # OpenShift AI/Data Science
      - name: rhods-operator
        channels:
          - name: stable

      #- name: openshift-pipelines-operator-rh
      #  channels:
      #    - name: latest
      - name: serverless-operator
        channels:
          - name: stable
      - name: servicemeshoperator
        channels:
          - name: stable
      # OpenShift Advanced Data Protection
      - name: redhat-oadp-operator
        channels:
          - name: stable
      # Advanced Cluster Management for Kubernetes
      - name: advanced-cluster-management
        channels:
          - name: release-2.15
          - name: release-2.14

      - name: multicluster-engine
        channels:
          - name: stable-2.10
          - name: stable-2.9

      # Node Feature Discovery Operatr
      - name: nfd

      # Advanced Cluster Security for Kubernetes
      - name: rhacs-operator
        channels:
          - name: stable

      # Quay
      - name: quay-operator
      - name: quay-bridge-operator
      - name: container-security-operator

      # Data Foundation
      - name: odf-operator
      - name: odf-operator-controller-manager
      - name: odf-csi-addons-operator
      - name: ocs-operator
      - name: mcg-operator
      - name: odf-dependencies
      - name: rook-ceph-operator
      - name: recipe
      - name: cephcsi-operator
      - name: ocs-client-operator
      - name: odf-prometheus-operator
      - name: odr-cluster-operator
      - name: odr-hub-operator
      - name: odf-multicluster-orchestrator

      # Local Storage Operator
      - name: lvms-operator
      - name: local-storage-operator

      # Dev Tooling
      - name: web-terminal
      - name: devworkspace-operator
      - name: devspaces

      # NMState Operator
      - name: kubernates-nmstate-operator
        channels:
          - name: stable

      # Update Service
      - name: cincinnati-operator
        channels:
          - name: v1

      # Pipelines
      - name: openshift-pipelines-operator-rh
        channels:
          - name: latest

      # GitOps
      - name: openshift-gitops-operator
        channels:
          - name: latest

      # Virt
      - name: kubevirt-hyperconverged
        channels:
          - name: stable
      - name: mtv-operator

      # Compliance Operator
      - name: compliance-operator
        channels:
          - name: stable

      # File Integrity Operator
      - name: file-integrity-operator
        channels:
          - name: stable

      # Ansible Automation Platform Operator
      - name: ansible-automation-platform-operator
        channels:
          - name: stable-2.6

      # MetalLB Operator
      - name: metallb-operator
        channels:
          - name: stable

      # PTP Operator
      - name: ptp-operator
        channels:
          - name: stable

      # Openshift Logging
      - name: cluster-logging
        channels:
          - name: stable-6.4

      - name: loki-operator
        channels:
          - name: stable-6.4

      # Cluster Observablility Operator
      - name: cluster-observability-operator
        channels:
          - name: stable

      # Network Observablility Operator
      - name: netobserv-operator
        channels:
          - name: stable

      # Keycloak Operator
      - name: rhbk-operator
        channels:
          - name: stable-v26.4

      # Cert Manager
      - name: openshift-cert-manager-operator
        channels:
          - name: stable-v1

    # Certified Operators Catalog
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.20
      packages:

      # Nginx Operator
      - name: nginx-ingress-operator
        channels:
          - name: alpha

      # Nutanix CSI Operator
      - name: nutanixcsioperator
        channels:
          - name: stable-3.x

      # Gitlab Operator
      - name: gitlab-operator-kubernetes
        channels:
          - name: stable
      - name: gitlab-runner-operator
        channels:
          - name: stable

    # Community Operators Catalog
    - catalog: registry.redhat.io/redhat/community-operator-index:v4.20
      packages:

      # MariaDB Operator
      - name: mariadb-operator

      # GroupSync Operator
      - name: group-sync-operator

  additionalImages:
  # Some standard tooling for debugging
  - name: registry.redhat.io/rhel9/support-tools:latest
  - name: registry.redhat.io/rhel8/rhel-guest-image:latest
  - name: registry.redhat.io/rhel9/rhel-guest-image:latest
  - name: registry.redhat.io/openshift4/ose-must-gather:latest
  - name: registry.redhat.io/ubi8/ubi:latest
  - name: registry.redhat.io/ubi9/ubi:latest
  - name: registry.redhat.io/ubi9/httpd-24:latest
  - name: registry.redhat.io/odf4/odf-must-gather-rhel9:v4.18
  - name: registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel9:v4.20
  - name: registry.redhat.io/ubi9/httpd-24:latest
  - name: registry.redhat.io/openshift4/ose-cli:latest

  # Jenkins Container
  - name: docker.io/jenkins/jenkins:latest

  # Postgres Database Images
  - name: registry.redhat.io/rhel9/postgresql-15:latest
  - name: registry.redhat.io/rhel9/postgresql-16:latest
